spring:
  redis:
  #指定数据库
    database: 0
    host: 127.0.0.1
    port: 6379
    #登陆密码
    password:
    jedis:
      pool:
      #连接池最大连接数
        max-active: 8
        #连接池最大空闲连接数
        max-idle: 8
        #连接池最小空闲连接数
        min-idle: 0
        #连接超时时间
        max-wait: -1ms